sudo: false
language: r

r: bioc-release

# python:
#   - 2.7.8
#   - 2.7.12

# perl:
#  - 5.16.3

cache:
  apt: true
  # directories:
  #   - $HOME/miniconda

# before_install:
#   # install miniconda for Python dependencies
#   - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
#   - chmod +x miniconda.sh
#   - ./miniconda.sh -b -p $HOME/miniconda -f
#   - export PATH=$HOME/miniconda/bin:$PATH
#   - conda update --yes conda
#   - conda info -a

# r_packages:
#   - edgeR
#   - DESeq2

before_install:
    - ./bioconda_INSTALL.sh

install:
  - Rscript -e 'install.packages(c("testthat"))'

script:
  - source ~/.bashrc
  - tail ~/.bashrc
  - hash -r
  - which samtools
  - which hisat2
  - cd test_data && sh test_whole_pipeline.sh && less pipeline_test/error.log && less pipeline_test/error.log

after_failure:
  - ls -l /home/travis/build/mshakya/PiReT/thirdParty/miniconda/bin /home/travis/build/mshakya/PiReT/thirdParty/miniconda/bin //home/travis/texlive/bin/x86_64-linux /home/travis/R-bin/bin

