sudo: false
language: perl

# r: bioc-release

# python:
#   - 2.7.8
#   - 2.7.12

perl:
 - 5.16.3

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  - pip install --user codecov

r_packages:
  - edgeR
  - DESeq2

install:
  #- Rscript -e 'install.packages(c("testthat"))'
  - conda install --yes -c bioconda hisat2=2.0.5
  - conda install --yes -c bioconda jellyfish=2.2.6
  - conda install --yes -c bioconda perl-parallel-forkmanager=1.17
  - conda install --yes -c bioconda bowtie2=2.2.8
  - conda install --yes -c bioconda bwa=0.7.15
  - conda install --yes -c bioconda htseq
  - conda install --yes -c bioconda samtools=1.3.1
  - conda install --yes -c bioconda perl-app-cpanminus
  - conda install --yes -c bioconda bedtools=2.26.0

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - ./bioconda_INSTALL.sh
# - cd test_data && sh test_pipeline_linux.sh
  - perl Makefile.PL
  - make
  - make test
  - cover -test

after_success:
  - cover -report codecov
