sudo: false
language: perl

perl:
  - "5.22"

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  - pip install --user codecov

install:
  - ./INSTALL-PiReTOME.sh

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
  - ls $HOME/ext/lib/perl5
  - echo $PATH
  - source $HOME/.bashrc
  - echo $PATH
  - perl Build.PL
  - ./Build test
  - cd test_data && sh test_pipeline_linux.sh
  - cover -test

after_success:
  - cover -report codecov
