sudo: false
language: perl

perl:
  - "5.22"

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  - pip install --user codecov

install:
  - ./INSTALL-PiReTOME.sh

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - export PATH=$PATH:bin/

script:
  - echo $PATH
  - perl Build.PL
  - ./Build test
  - ./Build testcover
  # - cd test_data && sh test_pipeline_linux.sh && cd ..
  # - cover -test

after_success:
  - cover -report codecov
