sudo: false
language: perl

perl:
  - "5.22"

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  - pip install --user codecov

install:
  - ./INSTALL-PiReTOME.sh

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - ls
  - perl Build.PL
  - ./Build test
  - cd test_data && sh test_pipeline_linux.sh
  - cover -test

after_success:
  - cover -report codecov
